// <auto-generated />

using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Query;
using Microsoft.Crm.Sdk.Messages;
using Microsoft.Xrm.Sdk.Messages;
using Microsoft.Xrm.Sdk.Metadata;
using Microsoft.Xrm.Sdk.Client;
using System.Threading.Tasks;
using System.ComponentModel;

namespace LicenseOrg.CsvRollup.ProxyClasses
{
    [EntityLogicalNameAttribute("xe0_dynamicsorganization")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XrmToolkit", "4.0")]
    public partial class xe0_DynamicsOrganization : BaseProxyClass
    {
        public new const string LogicalName = "xe0_dynamicsorganization";
        public const int ObjectTypeCode = 10013;
        public const string PrimaryIdAttribute = "xe0_dynamicsorganizationid";
        public const string PrimaryNameAttribute = "xe0_name";
        
        static xe0_DynamicsOrganization()
        {
            BaseProxyClass.RegisterProxyType(typeof(xe0_DynamicsOrganization), "xe0_dynamicsorganization");
            _textOptions = new Dictionary<string, eTextOptions>();
            _numberOptions = new Dictionary<string, eNumberOptions>();
            _errorStrings = new Dictionary<string, string>();
            TextError = "The value for attribute '{0}' cannot be longer than {3} characters. The length of the value is {2} characters.";
            NumberError = "The value for attribute '{0}' must be between {2} and {3}. The value is {1}";
        }
        public xe0_DynamicsOrganization() : base(new Entity("xe0_dynamicsorganization")) { }
        public xe0_DynamicsOrganization(Entity original) : base(original) { }
        public static string GetLogicalName() { return BaseProxyClass.GetLogicalName<xe0_DynamicsOrganization>(); }
        /// <summary>
        /// Action to perform when the string value is greater than the allowed length.
        /// <para>This is the default for any string attribute in this Entity</para>
        /// </summary>
        public static eTextOptions TextOptions { get; set; }
        private static Dictionary<string, eTextOptions> _textOptions;
        /// <summary>
        /// Use this to set an action and error string when a value is greater than the allowed length
        /// </summary>
        /// <param name="logicalName">Name of Attribute</param>
        /// <param name="options">Action to perform when the value is greater than the allowed length</param>
        /// <param name="errorString">Optional: Error to throw if the eTextOptions == ThrowError
        /// <para>If nothing is specified then the 'TextError' string is used.</para>
        /// <para>You may use the following parameters:</para>
        /// <para>{0} = Attribute Logical Name</para>
        /// <para>{1} = Value</para>
        /// <para>{2} = Length</para>
        /// <para>{3} = Max Length</para>
        /// </param>
        public static void SetTextOptions(string logicalName, eTextOptions options, string errorString = null)
        {
            if (_textOptions.ContainsKey(logicalName)) { _textOptions[logicalName] = options; }
            else { _textOptions.Add(logicalName, options); }
            if (!string.IsNullOrEmpty(errorString))
            {
                if (_errorStrings.ContainsKey(logicalName)) { _errorStrings[logicalName] = errorString; }
                else { _errorStrings.Add(logicalName, errorString); }
            }
            else if (_errorStrings.ContainsKey(logicalName)) { _errorStrings.Remove(logicalName); }
        }
        protected override eTextOptions GetTextOptions(string logicalName)
        {
            if (_textOptions.ContainsKey(logicalName)) { return _textOptions[logicalName]; }
            return TextOptions;
        }
        /// <summary>
        /// Action to perform when the number value is greater or less than the allowed value.
        /// <para>This is the default for any int, decimal, double, or money attribute in this Entity</para>
        /// </summary>
        public static eNumberOptions NumberOptions { get; set; }
        private static Dictionary<string, eNumberOptions> _numberOptions;
        /// <summary>
        /// Use this to set an action and error string when a value is greater or less than the allowed value
        /// </summary>
        /// <param name="logicalName">Name of Attribute</param>
        /// <param name="options">Action to perform when the value is greater or less than the allowed value</param>
        /// <param name="errorString">Optional: Error to throw if the eNumberOptions == ThrowError
        /// <para>If nothing is specified then the 'NumberError' string is used.</para>
        /// <para>You may use the following parameters:</para>
        /// <para>{0} = Attribute Logical Name</para>
        /// <para>{1} = Value</para>
        /// <para>{2} = Min Value</para>
        /// <para>{3} = Max Value</para>
        /// </param>
        public static void SetNumberOptions(string logicalName, eNumberOptions options, string errorString = null)
        {
            if (_numberOptions.ContainsKey(logicalName)) { _numberOptions[logicalName] = options; }
            else { _numberOptions.Add(logicalName, options); }
            if (!string.IsNullOrEmpty(errorString))
            {
                if (_errorStrings.ContainsKey(logicalName)) { _errorStrings[logicalName] = errorString; }
                else { _errorStrings.Add(logicalName, errorString); }
            }
            else if (_errorStrings.ContainsKey(logicalName)) { _errorStrings.Remove(logicalName); }
        }
        protected override eNumberOptions GetNumberOptions(string logicalName)
        {
            if (_numberOptions.ContainsKey(logicalName)) { return _numberOptions[logicalName]; }
            return NumberOptions;
        }
        private static Dictionary<string, string> _errorStrings;
        protected override string GetErrorString(string attributeName, BaseProxyClass.eErrorType defaultErrorType)
        {
            if (_errorStrings.ContainsKey(attributeName))
            {
                return _errorStrings[attributeName];
            }
            return defaultErrorType == BaseProxyClass.eErrorType.Text ? TextError : NumberError;
        }
        /// <summary>
        /// <para>Default error string is: The value for attribute '{0}' cannot be longer than {3} characters. The length of the value is {2} characters.</para>
        /// <para>You may use the following parameters</para>
        /// <para>{0} = Attribute Name</para>
        /// <para>{1} = Value</para>
        /// <para>{2} = Length</para>
        /// <para>{3} = Max Length</para>
        /// </summary>
        public static string TextError { get; set; }
        /// <summary>
        /// <para>Default error string is: The value for attribute '{0}' must be between {2} and {3}. The value is {1}.</para>
        /// <para>You may use the following parameters</para>
        /// <para>{0} = Attribute Name</para>
        /// <para>{1} = Value</para>
        /// <para>{2} = Min Value</para>
        /// <para>{3} = Max Value</para>
        /// </summary>
        public static string NumberError { get; set; }

        ///<summary>
///<para>Logical Name: createdonbehalfbyyominame</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("createdonbehalfbyyominame")]
public string CreatedOnBehalfByYomiName
{
	get { return this.GetPropertyValue<string>("createdonbehalfbyyominame"); }
}
///<summary>
///<para>Logical Name: owneridname</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("owneridname")]
public string OwnerIdName
{
	get { return this.GetPropertyValue<string>("owneridname"); }
}
///<summary>
///<para>Logical Name: xe0_accountidname</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("xe0_accountidname")]
public string xe0_AccountIdName
{
	get { return this.GetPropertyValue<string>("xe0_accountidname"); }
}
///<summary>
///<para>Logical Name: xe0_accountidyominame</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("xe0_accountidyominame")]
public string xe0_AccountIdYomiName
{
	get { return this.GetPropertyValue<string>("xe0_accountidyominame"); }
}
///<summary>
///<para>Logical Name: modifiedbyname</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("modifiedbyname")]
public string ModifiedByName
{
	get { return this.GetPropertyValue<string>("modifiedbyname"); }
}
///<summary>
///<para>Logical Name: modifiedbyyominame</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("modifiedbyyominame")]
public string ModifiedByYomiName
{
	get { return this.GetPropertyValue<string>("modifiedbyyominame"); }
}
///<summary>
///<para>Logical Name: createdbyyominame</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("createdbyyominame")]
public string CreatedByYomiName
{
	get { return this.GetPropertyValue<string>("createdbyyominame"); }
}
///<summary>
///<para>Logical Name: xe0_usercountunitidname</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("xe0_usercountunitidname")]
public string xe0_UserCountUnitIdName
{
	get { return this.GetPropertyValue<string>("xe0_usercountunitidname"); }
}
///<summary>
///<para>Logical Name: owneridtype</para>
///</summary>
[AttributeLogicalNameAttribute("owneridtype")]
public string OwnerIdType
{
	get { return this.GetPropertyValue<string>("owneridtype"); }
	set { this.SetPropertyValue<string>("owneridtype", value, "OwnerIdType"); }
}
///<summary>
///<para>Logical Name: owneridyominame</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("owneridyominame")]
public string OwnerIdYomiName
{
	get { return this.GetPropertyValue<string>("owneridyominame"); }
}
///<summary>
///<para>Logical Name: modifiedonbehalfbyyominame</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("modifiedonbehalfbyyominame")]
public string ModifiedOnBehalfByYomiName
{
	get { return this.GetPropertyValue<string>("modifiedonbehalfbyyominame"); }
}
///<summary>
///<para>Logical Name: createdbyname</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("createdbyname")]
public string CreatedByName
{
	get { return this.GetPropertyValue<string>("createdbyname"); }
}
///<summary>
///<para>Logical Name: createdonbehalfbyname</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("createdonbehalfbyname")]
public string CreatedOnBehalfByName
{
	get { return this.GetPropertyValue<string>("createdonbehalfbyname"); }
}
///<summary>
///<para>Logical Name: modifiedonbehalfbyname</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("modifiedonbehalfbyname")]
public string ModifiedOnBehalfByName
{
	get { return this.GetPropertyValue<string>("modifiedonbehalfbyname"); }
}
///<summary>
///<para>Logical Name: versionnumber</para>
///</summary>
[AttributeLogicalNameAttribute("versionnumber")]
public int? VersionNumber
{
	get { return this.GetPropertyValue<int?>("versionnumber"); }
}
///<summary>
///<para>Logical Name: xe0_accountid</para>
///</summary>
[AttributeLogicalNameAttribute("xe0_accountid")]
public EntityReference xe0_AccountId
{
	get { return this.GetPropertyValue<EntityReference>("xe0_accountid"); }
	set { this.SetPropertyValue<EntityReference>("xe0_accountid", value, "xe0_AccountId"); }
}
///<summary>
///<para>Logical Name: xe0_description</para>
///<para>Max Length: 150 characters</para>
///</summary>
[AttributeLogicalNameAttribute("xe0_description")]
public string xe0_Description
{
	get { return this.GetPropertyValue<string>("xe0_description"); }
	set { this.SetPropertyValue("xe0_description", value, 150, "xe0_Description"); }
}
///<summary>
///<para>Logical Name: createdby</para>
///</summary>
[AttributeLogicalNameAttribute("createdby")]
public EntityReference CreatedBy
{
	get { return this.GetPropertyValue<EntityReference>("createdby"); }
}
///<summary>
///<para>Logical Name: createdonbehalfby</para>
///</summary>
[AttributeLogicalNameAttribute("createdonbehalfby")]
public EntityReference CreatedOnBehalfBy
{
	get { return this.GetPropertyValue<EntityReference>("createdonbehalfby"); }
}
///<summary>
///<para>Logical Name: createdon</para>
///</summary>
[AttributeLogicalNameAttribute("createdon")]
public DateTime? CreatedOn
{
	get { return this.GetPropertyValue<DateTime?>("createdon"); }
}
///<summary>
///<para>Key Property (Uniqueidentifier)</para>
///<para>Logical Name: xe0_dynamicsorganizationid</para>
///</summary>
[AttributeLogicalNameAttribute("xe0_dynamicsorganizationid")]
public Guid xe0_DynamicsOrganizationId
{
	get
	{
		return this.Id;
	}
	set
	{
		this.Id = value;
	}
}
///<summary>
///<para>Logical Name: xe0_friendlyname</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("xe0_friendlyname")]
public string xe0_FriendlyName
{
	get { return this.GetPropertyValue<string>("xe0_friendlyname"); }
	set { this.SetPropertyValue("xe0_friendlyname", value, 100, "xe0_FriendlyName"); }
}
///<summary>
///<para>Logical Name: importsequencenumber</para>
///<para>Minimum Value: -2147483648</para>
///<para>Maximum Value: 2147483647</para>
///</summary>
[AttributeLogicalNameAttribute("importsequencenumber")]
public int? ImportSequenceNumber
{
	get { return this.GetPropertyValue<int?>("importsequencenumber"); }
	set { this.SetPropertyValue("importsequencenumber", (int?)value, (int)-2147483648, (int)2147483647, "ImportSequenceNumber"); }
}
/// <summary>
///Logical Name: xe0_hostingmodel
/// </summary>
[AttributeLogicalNameAttribute("xe0_hostingmodel")]
public eLocation? xe0_HostingModel
{
	get
	{
		if (xe0_HostingModel_OptionSetValue != null) { return (eLocation)xe0_HostingModel_OptionSetValue.Value; }
		return null;
	}
	set
	{
		if (value != null) { this.xe0_HostingModel_OptionSetValue = new OptionSetValue((int)value); }
		else this.xe0_HostingModel_OptionSetValue = null;
	}
}
///<summary>
///<para>Logical Name: xe0_hostingmodel</para>
///</summary>
[AttributeLogicalNameAttribute("xe0_hostingmodel")]
public OptionSetValue xe0_HostingModel_OptionSetValue
{
	get { return this.GetPropertyValue<OptionSetValue>("xe0_hostingmodel"); }
	set { this.SetPropertyValue<OptionSetValue>("xe0_hostingmodel", value, "xe0_HostingModel_OptionSetValue"); }
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="Service">CRM Organization Service</param>
/// <returns></returns>
public string xe0_HostingModel_Text(IOrganizationService Service)
{
	return this.xe0_HostingModel_OptionSetValue.GetOptionSetText(Service, this, "xe0_hostingmodel");
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
/// <returns></returns>
public string xe0_HostingModel_Text(EnumAttributeMetadata AttributeMetadata)
{
	return AttributeMetadata.GetOptionSetText(this.xe0_HostingModel_OptionSetValue.Value);
}
///<summary>
///<para>Logical Name: modifiedby</para>
///</summary>
[AttributeLogicalNameAttribute("modifiedby")]
public EntityReference ModifiedBy
{
	get { return this.GetPropertyValue<EntityReference>("modifiedby"); }
}
///<summary>
///<para>Logical Name: modifiedonbehalfby</para>
///</summary>
[AttributeLogicalNameAttribute("modifiedonbehalfby")]
public EntityReference ModifiedOnBehalfBy
{
	get { return this.GetPropertyValue<EntityReference>("modifiedonbehalfby"); }
}
///<summary>
///<para>Logical Name: modifiedon</para>
///</summary>
[AttributeLogicalNameAttribute("modifiedon")]
public DateTime? ModifiedOn
{
	get { return this.GetPropertyValue<DateTime?>("modifiedon"); }
}
///<summary>
///<para>Logical Name: xe0_name</para>
///<para>Max Length: 200 characters</para>
///</summary>
[AttributeLogicalNameAttribute("xe0_name")]
public string xe0_Name
{
	get { return this.GetPropertyValue<string>("xe0_name"); }
	set { this.SetPropertyValue("xe0_name", value, 200, "xe0_Name"); }
}
/// <summary>
///Logical Name: xe0_orgtype
/// </summary>
[AttributeLogicalNameAttribute("xe0_orgtype")]
public eOrgTypes? xe0_OrgType
{
	get
	{
		if (xe0_OrgType_OptionSetValue != null) { return (eOrgTypes)xe0_OrgType_OptionSetValue.Value; }
		return null;
	}
	set
	{
		if (value != null) { this.xe0_OrgType_OptionSetValue = new OptionSetValue((int)value); }
		else this.xe0_OrgType_OptionSetValue = null;
	}
}
///<summary>
///<para>Logical Name: xe0_orgtype</para>
///</summary>
[AttributeLogicalNameAttribute("xe0_orgtype")]
public OptionSetValue xe0_OrgType_OptionSetValue
{
	get { return this.GetPropertyValue<OptionSetValue>("xe0_orgtype"); }
	set { this.SetPropertyValue<OptionSetValue>("xe0_orgtype", value, "xe0_OrgType_OptionSetValue"); }
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="Service">CRM Organization Service</param>
/// <returns></returns>
public string xe0_OrgType_Text(IOrganizationService Service)
{
	return this.xe0_OrgType_OptionSetValue.GetOptionSetText(Service, this, "xe0_orgtype");
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
/// <returns></returns>
public string xe0_OrgType_Text(EnumAttributeMetadata AttributeMetadata)
{
	return AttributeMetadata.GetOptionSetText(this.xe0_OrgType_OptionSetValue.Value);
}
///<summary>
///<para>Logical Name: ownerid</para>
///</summary>
[AttributeLogicalNameAttribute("ownerid")]
public EntityReference OwnerId
{
	get { return this.GetPropertyValue<EntityReference>("ownerid"); }
	set { this.SetPropertyValue<EntityReference>("ownerid", value, "OwnerId"); }
}
///<summary>
///<para>Logical Name: owningbusinessunit</para>
///</summary>
[AttributeLogicalNameAttribute("owningbusinessunit")]
public EntityReference OwningBusinessUnit
{
	get { return this.GetPropertyValue<EntityReference>("owningbusinessunit"); }
}
///<summary>
///<para>Logical Name: owningteam</para>
///</summary>
[AttributeLogicalNameAttribute("owningteam")]
public EntityReference OwningTeam
{
	get { return this.GetPropertyValue<EntityReference>("owningteam"); }
}
///<summary>
///<para>Logical Name: owninguser</para>
///</summary>
[AttributeLogicalNameAttribute("owninguser")]
public EntityReference OwningUser
{
	get { return this.GetPropertyValue<EntityReference>("owninguser"); }
}
///<summary>
///<para>Logical Name: overriddencreatedon</para>
///</summary>
[AttributeLogicalNameAttribute("overriddencreatedon")]
public DateTime? OverriddenCreatedOn
{
	get { return this.GetPropertyValue<DateTime?>("overriddencreatedon"); }
	set { this.SetPropertyValue<DateTime?>("overriddencreatedon", value, "OverriddenCreatedOn"); }
}
/// <summary>
///Logical Name: statecode
/// </summary>
[AttributeLogicalNameAttribute("statecode")]
public eStatus? statecode
{
	get
	{
		if (statecode_OptionSetValue != null) { return (eStatus)statecode_OptionSetValue.Value; }
		return null;
	}
	set
	{
		if (value != null) { this.statecode_OptionSetValue = new OptionSetValue((int)value); }
		else this.statecode_OptionSetValue = null;
	}
}
///<summary>
///<para>Logical Name: statecode</para>
///</summary>
[AttributeLogicalNameAttribute("statecode")]
public OptionSetValue statecode_OptionSetValue
{
	get { return this.GetPropertyValue<OptionSetValue>("statecode"); }
	set { this.SetPropertyValue<OptionSetValue>("statecode", value, "statecode_OptionSetValue"); }
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="Service">CRM Organization Service</param>
/// <returns></returns>
public string statecode_Text(IOrganizationService Service)
{
	return this.statecode_OptionSetValue.GetOptionSetText(Service, this, "statecode");
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
/// <returns></returns>
public string statecode_Text(EnumAttributeMetadata AttributeMetadata)
{
	return AttributeMetadata.GetOptionSetText(this.statecode_OptionSetValue.Value);
}
/// <summary>
///Logical Name: statuscode
/// </summary>
[AttributeLogicalNameAttribute("statuscode")]
public eStatusReason? statuscode
{
	get
	{
		if (statuscode_OptionSetValue != null) { return (eStatusReason)statuscode_OptionSetValue.Value; }
		return null;
	}
	set
	{
		if (value != null) { this.statuscode_OptionSetValue = new OptionSetValue((int)value); }
		else this.statuscode_OptionSetValue = null;
	}
}
///<summary>
///<para>Logical Name: statuscode</para>
///</summary>
[AttributeLogicalNameAttribute("statuscode")]
public OptionSetValue statuscode_OptionSetValue
{
	get { return this.GetPropertyValue<OptionSetValue>("statuscode"); }
	set { this.SetPropertyValue<OptionSetValue>("statuscode", value, "statuscode_OptionSetValue"); }
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="Service">CRM Organization Service</param>
/// <returns></returns>
public string statuscode_Text(IOrganizationService Service)
{
	return this.statuscode_OptionSetValue.GetOptionSetText(Service, this, "statuscode");
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
/// <returns></returns>
public string statuscode_Text(EnumAttributeMetadata AttributeMetadata)
{
	return AttributeMetadata.GetOptionSetText(this.statuscode_OptionSetValue.Value);
}
///<summary>
///<para>Logical Name: timezoneruleversionnumber</para>
///<para>Minimum Value: -1</para>
///<para>Maximum Value: 2147483647</para>
///</summary>
[AttributeLogicalNameAttribute("timezoneruleversionnumber")]
public int? TimeZoneRuleVersionNumber
{
	get { return this.GetPropertyValue<int?>("timezoneruleversionnumber"); }
	set { this.SetPropertyValue("timezoneruleversionnumber", (int?)value, (int)-1, (int)2147483647, "TimeZoneRuleVersionNumber"); }
}
///<summary>
///<para>Logical Name: xe0_uniquename</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("xe0_uniquename")]
public string xe0_UniqueName
{
	get { return this.GetPropertyValue<string>("xe0_uniquename"); }
	set { this.SetPropertyValue("xe0_uniquename", value, 100, "xe0_UniqueName"); }
}
///<summary>
///<para>Logical Name: xe0_usercount</para>
///<para>Minimum Value: 1</para>
///<para>Maximum Value: 2147483647</para>
///</summary>
[AttributeLogicalNameAttribute("xe0_usercount")]
public int? xe0_UserCount
{
	get { return this.GetPropertyValue<int?>("xe0_usercount"); }
	set { this.SetPropertyValue("xe0_usercount", (int?)value, (int)1, (int)2147483647, "xe0_UserCount"); }
}
///<summary>
///<para>Logical Name: xe0_usercountunitid</para>
///</summary>
[AttributeLogicalNameAttribute("xe0_usercountunitid")]
public EntityReference xe0_UserCountUnitId
{
	get { return this.GetPropertyValue<EntityReference>("xe0_usercountunitid"); }
	set { this.SetPropertyValue<EntityReference>("xe0_usercountunitid", value, "xe0_UserCountUnitId"); }
}
///<summary>
///<para>Logical Name: utcconversiontimezonecode</para>
///<para>Minimum Value: -1</para>
///<para>Maximum Value: 2147483647</para>
///</summary>
[AttributeLogicalNameAttribute("utcconversiontimezonecode")]
public int? UTCConversionTimeZoneCode
{
	get { return this.GetPropertyValue<int?>("utcconversiontimezonecode"); }
	set { this.SetPropertyValue("utcconversiontimezonecode", (int?)value, (int)-1, (int)2147483647, "UTCConversionTimeZoneCode"); }
}


        /// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_ActivityPointers</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_ActivityPointers (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "activitypointer", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_ActivityPointers</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_ActivityPointers (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "activitypointer", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity (Regarding)</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_Annotations</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_Annotations (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "annotation", "objectid", Columns); }
/// <summary>
/// <para><b>Entity (Regarding)</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_Annotations</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_Annotations (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "annotation", "objectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_Appointments</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_Appointments (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "appointment", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_Appointments</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_Appointments (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "appointment", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_AsyncOperations</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_AsyncOperations (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "asyncoperation", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_AsyncOperations</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_AsyncOperations (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "asyncoperation", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_BulkDeleteFailures</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_BulkDeleteFailures (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "bulkdeletefailure", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_BulkDeleteFailures</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_BulkDeleteFailures (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "bulkdeletefailure", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_connections1</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_connections1 (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "connection", "record1id", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_connections1</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_connections1 (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "connection", "record1id", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_connections2</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_connections2 (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "connection", "record2id", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_connections2</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_connections2 (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "connection", "record2id", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_DuplicateBaseRecord</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_DuplicateBaseRecord (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "duplicaterecord", "baserecordid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_DuplicateBaseRecord</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_DuplicateBaseRecord (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "duplicaterecord", "baserecordid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_DuplicateMatchingRecord</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_DuplicateMatchingRecord (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "duplicaterecord", "duplicaterecordid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_DuplicateMatchingRecord</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_DuplicateMatchingRecord (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "duplicaterecord", "duplicaterecordid", Columns); }
/// <summary>
/// <para><b>Entity (Regarding)</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_Emails</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_Emails (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "email", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity (Regarding)</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_Emails</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_Emails (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "email", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_Faxes</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_Faxes (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "fax", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_Faxes</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_Faxes (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "fax", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_Feedback</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_Feedback (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "feedback", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_Feedback</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_Feedback (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "feedback", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_Letters</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_Letters (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "letter", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_Letters</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_Letters (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "letter", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_MailboxTrackingFolders</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_MailboxTrackingFolders (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "mailboxtrackingfolder", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_MailboxTrackingFolders</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_MailboxTrackingFolders (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "mailboxtrackingfolder", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_PhoneCalls</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_PhoneCalls (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "phonecall", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_PhoneCalls</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_PhoneCalls (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "phonecall", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_PrincipalObjectAttributeAccesses</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_PrincipalObjectAttributeAccesses (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "principalobjectattributeaccess", "objectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_PrincipalObjectAttributeAccesses</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_PrincipalObjectAttributeAccesses (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "principalobjectattributeaccess", "objectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_ProcessSession</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_ProcessSession (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "processsession", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_ProcessSession</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_ProcessSession (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "processsession", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_RecurringAppointmentMasters</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_RecurringAppointmentMasters (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "recurringappointmentmaster", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_RecurringAppointmentMasters</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_RecurringAppointmentMasters (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "recurringappointmentmaster", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_ServiceAppointments</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_ServiceAppointments (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "serviceappointment", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_ServiceAppointments</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_ServiceAppointments (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "serviceappointment", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_SocialActivities</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_SocialActivities (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "socialactivity", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_SocialActivities</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_SocialActivities (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "socialactivity", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_SyncErrors</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_SyncErrors (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "syncerror", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_SyncErrors</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_SyncErrors (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "syncerror", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_Tasks</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_Tasks (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "task", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_Tasks</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_Tasks (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "task", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_UserEntityInstanceDatas</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_UserEntityInstanceDatas (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "userentityinstancedata", "objectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: xe0_dynamicsorganization_UserEntityInstanceDatas</para>
/// </summary>
public List<Entity> xe0_dynamicsorganization_UserEntityInstanceDatas (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "userentityinstancedata", "objectid", Columns); }
/// <summary>
/// <para><b>xe0_LicenseOrg (Org)</b></para>
/// <para>Schema Name: xe0_xe0_dynamicsorganization_xe0_licenseorg</para>
/// </summary>
public List<xe0_LicenseOrg> xe0_xe0_dynamicsorganization_xe0_licenseorg (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<xe0_LicenseOrg>(Service, this.Id, "xe0_licenseorg", "xe0_orgid", Columns); }
/// <summary>
/// <para><b>xe0_LicenseOrg (Org)</b></para>
/// <para>Schema Name: xe0_xe0_dynamicsorganization_xe0_licenseorg</para>
/// </summary>
public List<xe0_LicenseOrg> xe0_xe0_dynamicsorganization_xe0_licenseorg (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<xe0_LicenseOrg>(Service, this.Id, "xe0_licenseorg", "xe0_orgid", Columns); }


        /// <summary>
/// <para>Related Entity: <b>Order Product</b></para>
/// <para>N:N Relationship</para>
/// <para>Schema Name: xe0_salesorderdetail_xe0_dynamicsorganization</para>
/// </summary>
public List<Entity> Getxe0_salesorderdetail_xe0_dynamicsorganization (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedManyToManyEntities(Service, this, "xe0_dynamicsorganization", "xe0_dynamicsorganizationid", "salesorderdetail", "salesorderdetailid", "xe0_salesorderdetail_xe0_dynamicsorg", "xe0_dynamicsorganizationid", "salesorderdetailid", Columns); }
public List<Entity> Getxe0_salesorderdetail_xe0_dynamicsorganization (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedManyToManyEntities(Service, this, "xe0_dynamicsorganization", "xe0_dynamicsorganizationid", "salesorderdetail", "salesorderdetailid", "xe0_salesorderdetail_xe0_dynamicsorg", "xe0_dynamicsorganizationid", "salesorderdetailid", Columns); }
public void Relatexe0_salesorderdetail_xe0_dynamicsorganization (IOrganizationService Service, params Entity[] Items) { Service.RelateEntities(this, "xe0_salesorderdetail_xe0_dynamicsorganization", Items); }
public void Relatexe0_salesorderdetail_xe0_dynamicsorganization (IOrganizationService Service, params EntityReference[] Items) { Service.RelateEntities(this, "xe0_salesorderdetail_xe0_dynamicsorganization", Items); }
public void UnRelatexe0_salesorderdetail_xe0_dynamicsorganization (IOrganizationService Service, params Entity[] Items) { Service.UnRelateEntities(this, "xe0_salesorderdetail_xe0_dynamicsorganization", Items); }
public void UnRelatexe0_salesorderdetail_xe0_dynamicsorganization (IOrganizationService Service, params EntityReference[] Items) { Service.UnRelateEntities(this, "xe0_salesorderdetail_xe0_dynamicsorganization", Items); }


        

        public enum eLocation
{
	///<summary><para>Online</para>
	///<para>Value = 1</para></summary>
	[Description("Online")]
	Online = 1, 
	///<summary><para>On-Prem</para>
	///<para>Value = 2</para></summary>
	[Description("On-Prem")]
	On_Prem = 2, 
	///<summary><para>Partner Hosted</para>
	///<para>Value = 3</para></summary>
	[Description("Partner Hosted")]
	PartnerHosted = 3
}
public enum eOrgTypes
{
	///<summary><para>Prod</para>
	///<para>Value = 1</para></summary>
	[Description("Prod")]
	Prod = 1, 
	///<summary><para>Dev</para>
	///<para>Value = 2</para></summary>
	[Description("Dev")]
	Dev = 2
}
public enum eStatus
{
	///<summary><para>Active</para>
	///<para>Value = 0</para></summary>
	[Description("Active")]
	Active = 0, 
	///<summary><para>Inactive</para>
	///<para>Value = 1</para></summary>
	[Description("Inactive")]
	Inactive = 1
}
public enum eStatusReason
{
	///<summary><para>Active</para>
	///<para>Value = 1</para></summary>
	[Description("Active")]
	Active_Active = 1, 
	///<summary><para>Inactive</para>
	///<para>Value = 2</para></summary>
	[Description("Inactive")]
	Inactive_Inactive = 2
}
public void SetState(IOrganizationService Service, eStatus State, eStatusReason Status)
{
	Service.SetState(this, (int)State, (int)Status);
}
public async System.Threading.Tasks.Task SetStateAsync(IOrganizationService Service, eStatus State, eStatusReason Status)
{
	 await Service.SetStateAsync(this, (int)State, (int)Status);
}


        public static class Properties
{
	/// <summary><para>createdonbehalfbyyominame</para>
	/// <para>createdonbehalfbyyominame</para></summary>
	public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
	/// <summary><para>owneridname</para>
	/// <para>owneridname</para></summary>
	public const string OwnerIdName = "owneridname";
	/// <summary><para>xe0_accountidname</para>
	/// <para>xe0_accountidname</para></summary>
	public const string xe0_AccountIdName = "xe0_accountidname";
	/// <summary><para>xe0_accountidyominame</para>
	/// <para>xe0_accountidyominame</para></summary>
	public const string xe0_AccountIdYomiName = "xe0_accountidyominame";
	/// <summary><para>modifiedbyname</para>
	/// <para>modifiedbyname</para></summary>
	public const string ModifiedByName = "modifiedbyname";
	/// <summary><para>modifiedbyyominame</para>
	/// <para>modifiedbyyominame</para></summary>
	public const string ModifiedByYomiName = "modifiedbyyominame";
	/// <summary><para>createdbyyominame</para>
	/// <para>createdbyyominame</para></summary>
	public const string CreatedByYomiName = "createdbyyominame";
	/// <summary><para>xe0_usercountunitidname</para>
	/// <para>xe0_usercountunitidname</para></summary>
	public const string xe0_UserCountUnitIdName = "xe0_usercountunitidname";
	/// <summary><para>owneridtype</para>
	/// <para>owneridtype</para></summary>
	public const string OwnerIdType = "owneridtype";
	/// <summary><para>owneridyominame</para>
	/// <para>owneridyominame</para></summary>
	public const string OwnerIdYomiName = "owneridyominame";
	/// <summary><para>modifiedonbehalfbyyominame</para>
	/// <para>modifiedonbehalfbyyominame</para></summary>
	public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
	/// <summary><para>createdbyname</para>
	/// <para>createdbyname</para></summary>
	public const string CreatedByName = "createdbyname";
	/// <summary><para>createdonbehalfbyname</para>
	/// <para>createdonbehalfbyname</para></summary>
	public const string CreatedOnBehalfByName = "createdonbehalfbyname";
	/// <summary><para>modifiedonbehalfbyname</para>
	/// <para>modifiedonbehalfbyname</para></summary>
	public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
	/// <summary><para>versionnumber</para>
	/// <para>versionnumber</para></summary>
	public const string VersionNumber = "versionnumber";
	/// <summary><para>Account</para>
	/// <para>xe0_accountid</para></summary>
	public const string xe0_AccountId = "xe0_accountid";
	/// <summary><para>Brief Description</para>
	/// <para>xe0_description</para></summary>
	public const string xe0_Description = "xe0_description";
	/// <summary><para>Created By</para>
	/// <para>createdby</para></summary>
	public const string CreatedBy = "createdby";
	/// <summary><para>Created By (Delegate)</para>
	/// <para>createdonbehalfby</para></summary>
	public const string CreatedOnBehalfBy = "createdonbehalfby";
	/// <summary><para>Created On</para>
	/// <para>createdon</para></summary>
	public const string CreatedOn = "createdon";
	/// <summary><para>CRM Org</para>
	/// <para>xe0_dynamicsorganizationid</para></summary>
	public const string xe0_DynamicsOrganizationId = "xe0_dynamicsorganizationid";
	/// <summary><para>Friendly Name</para>
	/// <para>xe0_friendlyname</para></summary>
	public const string xe0_FriendlyName = "xe0_friendlyname";
	/// <summary><para>Import Sequence Number</para>
	/// <para>importsequencenumber</para></summary>
	public const string ImportSequenceNumber = "importsequencenumber";
	/// <summary><para>Location</para>
	/// <para>xe0_hostingmodel</para></summary>
	public const string xe0_HostingModel = "xe0_hostingmodel";
	/// <summary><para>Modified By</para>
	/// <para>modifiedby</para></summary>
	public const string ModifiedBy = "modifiedby";
	/// <summary><para>Modified By (Delegate)</para>
	/// <para>modifiedonbehalfby</para></summary>
	public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
	/// <summary><para>Modified On</para>
	/// <para>modifiedon</para></summary>
	public const string ModifiedOn = "modifiedon";
	/// <summary><para>Name</para>
	/// <para>xe0_name</para></summary>
	public const string xe0_Name = "xe0_name";
	/// <summary><para>Org Type</para>
	/// <para>xe0_orgtype</para></summary>
	public const string xe0_OrgType = "xe0_orgtype";
	/// <summary><para>Owner</para>
	/// <para>ownerid</para></summary>
	public const string OwnerId = "ownerid";
	/// <summary><para>Owning Business Unit</para>
	/// <para>owningbusinessunit</para></summary>
	public const string OwningBusinessUnit = "owningbusinessunit";
	/// <summary><para>Owning Team</para>
	/// <para>owningteam</para></summary>
	public const string OwningTeam = "owningteam";
	/// <summary><para>Owning User</para>
	/// <para>owninguser</para></summary>
	public const string OwningUser = "owninguser";
	/// <summary><para>Record Created On</para>
	/// <para>overriddencreatedon</para></summary>
	public const string OverriddenCreatedOn = "overriddencreatedon";
	/// <summary><para>Status</para>
	/// <para>statecode</para></summary>
	public const string statecode = "statecode";
	/// <summary><para>Status Reason</para>
	/// <para>statuscode</para></summary>
	public const string statuscode = "statuscode";
	/// <summary><para>Time Zone Rule Version Number</para>
	/// <para>timezoneruleversionnumber</para></summary>
	public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
	/// <summary><para>UniqueName</para>
	/// <para>xe0_uniquename</para></summary>
	public const string xe0_UniqueName = "xe0_uniquename";
	/// <summary><para>User Count</para>
	/// <para>xe0_usercount</para></summary>
	public const string xe0_UserCount = "xe0_usercount";
	/// <summary><para>User Count Unit</para>
	/// <para>xe0_usercountunitid</para></summary>
	public const string xe0_UserCountUnitId = "xe0_usercountunitid";
	/// <summary><para>UTC Conversion Time Zone Code</para>
	/// <para>utcconversiontimezonecode</para></summary>
	public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
}

    }
}
